name: flutter_floating_particles
description: Animated particle effects for Flutter. Snow, rain, confetti, fireworks, hearts and more, with emitters, bursts, physics, touch interaction, images, SVGs and widgets.
version: 2.0.0
homepage: https://github.com/nitesh695/flutter_floating_particles
repository: https://github.com/nitesh695/flutter_floating_particles
issue_tracker: https://github.com/nitesh695/flutter_floating_particles/issues

topics:
  - particles
  - animation
  - effects
  - confetti
  - ui

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
